import endent from "endent"
import { ValidCNSInputs } from "../../../../create-next-stack-types"
import { getProjectNameOfPath } from "../../../../helpers/get-project-name-of-path"

export const generateIndexPage = (inputs: ValidCNSInputs) => endent/* tsx */ `
  import { NextPage } from "next";
  import Page from "../components/Page";
  import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";

  const Index: NextPage = () => {
    return (
      <Page
        title="${getProjectNameOfPath(inputs.args.appName)}"
        description="Generated by Create Next Stack."
      >
        <LandingPageTemplate />
      </Page>
    );
  };

  export default Index;
`
