import fs from "fs/promises"
import { constrain } from "../../helpers/constrain"
import { remove } from "../../helpers/remove"
import { Step } from "../../plugin"

/**
 * Removes the content generated by the official Create Next App CLI tool.
 */
export const removeOfficialCNAContentStep = constrain<Step>()({
  description: "removing content added by the Create Next App CLI tool",
  run: async () => {
    await Promise.all([
      remove("pages"),
      remove("styles"),
      remove("public/vercel.svg"),
    ])
    await fs.mkdir("pages")
  },
})
