import { promises as fs } from "fs"
import { remove } from "../../helpers/remove"
import { Step } from "../step"

/**
 * Removes the content generated by the official Create Next App CLI tool.
 */
export const removeOfficialCNAContentStep: Step = {
  description: "removing content added by the Create Next App CLI tool",

  shouldRun: async () => true,

  didRun: false,

  run: async () => {
    await Promise.all([
      remove("pages"),
      remove("styles"),
      remove("public/vercel.svg"),
    ])
    await fs.mkdir("pages")
  },
}
