import { throwError } from "../../error-handling"
import { remove } from "../../helpers/remove"
import { Step } from "../step"

/**
 * Removes the content generated by the official Create Next App CLI tool.
 */
export const removeOfficialCNAContentStep: Step = {
  shouldRun: function (this) {
    return true
  },

  run: async function (this) {
    this.log("Cleaning up official Next.js boilerplate...")

    try {
      await Promise.all([
        remove(`pages`), // TODO: Remove only files in pages
        remove(`styles`),
        remove(`public/vercel.svg`),
        // TODO: Remove README.md when/if another one is generated.
      ])
    } catch (error) {
      throwError.call(
        this,
        "An error occurred while removing the content generated by the official Create Next App CLI tool.",
        error
      )
    }
  },
}
