import aldent from "aldent"
import { ValidCNSInputs } from "../../../../create-next-stack-types.ts"
import { getProjectNameOfPath } from "../../../../helpers/get-project-name-of-path.ts"
import { nonNull } from "../../../../helpers/non-null.ts"
import { filterPlugins } from "../../../../setup/setup.ts"

export const generateLayout = async (
  inputs: ValidCNSInputs,
): Promise<string> => {
  const filteredPlugins = await filterPlugins(inputs)

  const imports = filteredPlugins
    .map((plugin) => plugin.slots?.appLayout?.imports)
    .filter(nonNull)
    .join("\n")

  const afterImports = filteredPlugins
    .map((plugin) => plugin.slots?.appLayout?.afterImports)
    .filter(nonNull)
    .join("\n")

  const htmlAttributes = filteredPlugins
    .map((plugin) => plugin.slots?.appLayout?.htmlAttributes)
    .filter(nonNull)
    .join(" ")

  const headContent = filteredPlugins
    .map((plugin) => plugin.slots?.appLayout?.headContent)
    .filter(nonNull)
    .join("\n")

  const bodyAttributes = filteredPlugins
    .map((plugin) => plugin.slots?.appLayout?.bodyAttributes)
    .filter(nonNull)
    .join(" ")

  const hasProviders = filteredPlugins.some(
    (plugin) =>
      plugin.slots?.appLayout?.providerImports ||
      plugin.slots?.appLayout?.providersStart ||
      plugin.slots?.appLayout?.providersEnd,
  )

  const projectName = getProjectNameOfPath(inputs.args.app_name)

  const providerImport = hasProviders
    ? `import { Providers } from "./providers.tsx";`
    : ""
  const childrenWithProviders = hasProviders
    ? aldent`
        <Providers>
          {children}
        </Providers>
      `
    : "{children}"

  return aldent`
    import type { Metadata } from "next";
    ${providerImport}
    ${imports}

    ${afterImports}

    export const metadata: Metadata = {
      title: "${projectName}",
      description: "Generated by Create Next Stack.",
    };

    export default function RootLayout({
      children,
    }: Readonly<{
      children: React.ReactNode;
    }>) {
      return (
        <html lang="en" ${htmlAttributes}>
          ${headContent ? aldent`<head>${headContent}</head>` : ""}
          <body ${bodyAttributes}>
            ${childrenWithProviders}
          </body>
        </html>
      );
    }
  `
}
