import Script from "next/script";
import { Paragraph } from "./components/Paragraph";
import { Section } from "./components/Section";
import { Subtitle } from "./components/Subtitle";
import { Title } from "./components/Title";
import styles from "./LandingPageTemplate.module.css";

const LandingPageTemplate = () => {
  const onConfettiLoad = () => {
    setTimeout(() => {
      const colors = [
        "#26ccff",
        "#a25afd",
        "#ff5e7e",
        "#88ff5a",
        "#fcff42",
        "#ffa62d",
        "#ff36ff",
      ];
      var end = Date.now() + 5 * 1000;

      (function frame() {
        (window as any).confetti({
          particleCount: colors.length,
          angle: 60,
          spread: 55,
          origin: { x: 0, y: 0.6 },
          colors,
        });
        (window as any).confetti({
          particleCount: colors.length,
          angle: 120,
          spread: 55,
          origin: { x: 1, y: 0.6 },
          colors,
        });

        if (Date.now() < end) {
          setTimeout(() => {
            requestAnimationFrame(frame);
          }, 50);
        }
      })();
    }, 1000);
  };

  return (
    <>
      <Script
        src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.4.0/dist/confetti.browser.min.js"
        strategy="afterInteractive"
        onLoad={onConfettiLoad}
      />
      <main>
        <Section>
          <Title>Your project is a go! 🎉</Title>
          <Subtitle>
            Get started by editing{" "}
            <code className={styles.inlineCode}>pages/index.tsx</code>
          </Subtitle>
        </Section>
        <Section className={styles.grayBackground}>
          <h2 className={styles.h2}>Learning resources</h2>
          <Paragraph>
            If you are using a technology for the first time, you can find
            related links in the generated{" "}
            <code className={styles.inlineCode}>README.md</code> file that might
            prove helpful.
          </Paragraph>
        </Section>
      </main>
      <footer>
        <Section>
          <Paragraph>
            Generated by{" "}
            <a href="https://github.com/akd-io/create-next-stack">
              Create Next Stack
            </a>
          </Paragraph>
        </Section>
      </footer>
    </>
  );
};

export default LandingPageTemplate;
