import aldent from "aldent"
import { ValidCNSInputs } from "../../../../create-next-stack-types.ts"
import { getProjectNameOfPath } from "../../../../helpers/get-project-name-of-path.ts"

export const generateIndexPage = ({ args }: ValidCNSInputs): string => aldent`
  import { NextPage } from "next";
  import Head from "next/head";
  import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate.tsx";

  const Index: NextPage = () => {
    return (
      <>
        <Head>
          <title>${getProjectNameOfPath(args.app_name)}</title>
          <meta name="description" content="Generated by Create Next Stack." />
        </Head>
        <LandingPageTemplate />
      </>
    );
  };

  export default Index;
`
